
export type PayRollType = {
    uuid?: string,
    emp_id?: string,
    hr_id?: string,
    created_month?: string | Date,
    worked_days?: number,
    loss_of_pay?: number,
    paid_days?: number,
    arrear_days?: number,
    ctc?: number,
    basic_pay?: number,
    hra?: number,
    conveyance?: number,
    medical?: number,
    performance?: number,
    city?: number,
    pf_employee?: number,
    pf_employer?: number,
    gratuity?: number,
    net_salary?: number,
    gross_total?: number,
    total_statutory?: number,
    cost_of_company?: number,
    employee_uuid?: string,
}
