export type HrProfileType = {
    id?: number,
    auth_id?: string,
    uuid?: string,
    emp_id?: string,
    first_name?: string,
    last_name?: string,
    department?: any[],
    contact_info?: {
        email?: string,
        phone?: string,
        address?: string,
    },
    join_date?: string,
    experience?: string,
    ctc?: number,
    dob?: string,
    emg_contact?: string,
    father_name?: string,
    qualification?: {
        degree?: string,
        specialization?: string,
        year_of_completion?: string,
        percentage?: string
    },
    pf_acc: string,
    pf_active?: boolean,
    image?: string,
    is_active?: boolean,
    password?: string,
}