export type EmployeeProfile = {
    uuid?: string,
    auth_id?: string,
    emp_id?: string,
    first_name?: string,
    last_name?: string,
    contact_info?: {
        email?: string,
        phone?: string,
        address1?: string,
        address2?: string,
        city?: string,
        state?: string,
        region?: string,
    },
    department?: any,
    emp_role?: string,
    payroll_slip?: any[],
    ctc?: number,
    qualification?: {
        degree?: string,
        specialization?: string,
        year_of_completion?: string,
        percentage?: string
    },
    join_date?: string,
    pf_active?: boolean,
    dob?: string,
    work_mode?: string,
    lpa?: number,
    image?: string,
    is_active?: boolean,
    password?: string,
}